name: Build and push to ECR

on:
  push:
    branches: [ dev ] # single branch for development

permissions:
  id-token: write # required for OIDC
  contents: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ 'dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check secrets and variables are set
        run: |
          if [ -z "${{ secrets.AWS_ROLE_ARN }}" ]; then
            echo "::error::AWS_ROLE_ARN not set"
            exit 1
          fi
          if [ -z "${{ vars.AWS_REGION }}" ]; then
            echo "::error::AWS_REGION not set"
            exit 1
          fi

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Capture version info
        id: version
        run: |
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "version=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push Nakama runtime
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          provenance: false
          sbom: false
          build-args: |
            commit=${{ steps.version.outputs.commit }}
            version=${{ steps.version.outputs.version }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/skgm.nakama:latest
            ${{ steps.login-ecr.outputs.registry }}/skgm.nakama:${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Nakama plugin builder image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./build/pluginbuilder/Dockerfile
          push: true
          provenance: false
          sbom: false
          build-args: |
            version=${{ steps.version.outputs.version }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/skgm.nakama-plugin-builder:latest
            ${{ steps.login-ecr.outputs.registry }}/skgm.nakama-plugin-builder:${{ steps.version.outputs.version }}
          cache-from: type=gha,scope=pluginbuilder
          cache-to: type=gha,mode=max,scope=pluginbuilder
