name: Build and push to ECR

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:    
    - run: echo "Workflow on default branch is a stub. Run from a feature branch to do real work."
